### ISSUE TITLE
Update to PMD 7.0

### ISSUE THREAD

**Issue by Tenebrosful** [cracrayol/vscode-java-pmd#1]
**Is your feature request related to a problem? Please describe.**
I planning to switch from Eclipse to VSCode and some rules aren't found, probably because we was using PMD 7.0 (Like UnnecessaryBoxing or NonSerializableClass)

**Describe the solution you'd like**
Updating the extension to fit the 7.0 PMD version.

**Comment by cracrayol** [comment]
Have you tried to use pmdBinPath/rulesets parameters ? It allows you to override the default pmd binaries and use your own ruleset.

**Comment by Tenebrosful** [comment]
UnnecessaryBoxing was added in PMD 7.0 https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#unnecessaryboxing

I don't know for the other, but anyway will be nice to update to PMD 7.0 and point to the new doc

**Comment by Tenebrosful** [comment]
I saw that you have upgrade bash script to upgrade it, i will take a look later to create a pull request

**Comment by cracrayol** [comment]
PMD 7 have some breaking changes (net.sourceforge.pmd.PMD was removed, for example).

I will update the code and put a new vsix here on github. I will put the version on marketplace only when 7.0.0 will be released.

**Comment by cracrayol** [comment]
You can try 0.7.0-rc (with PMD 7.0.0-rc3) here : https://github.com/cracrayol/vscode-java-pmd/releases/tag/v0.7.0-rc

Tell me if it's working well.

**Comment by Tenebrosful** [comment]
Ho sorry didn't notice that 7.0 was pre-release, i will take a look thanks !

**Comment by Tenebrosful** [comment]
Looks fine but i still don't know why it can't find [NonSerializableClass](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/NonSerializableClassRule.java) and [UnnecessaryBoxing](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryBoxingRule.java) that's really strange, idk if it's a pmd issue or vscode-pmd issue

[My complete .ruleset.xml](https://gist.github.com/Tenebrosful/8a5b517064e427727a0198018eed1584)

```
Analyzing c:\x\Sources\x\x\WEB-INF\src\Portail\GestionnaireFavoris.java
stderr:juin 09, 2023 2:08:50 PM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
SEVERE: Cannot load ruleset c:\x\x\x\x\.ruleset.xml: Unable to find referenced rule UnnecessaryBoxing; perhaps the rule name is misspelled?

stderr:juin 09, 2023 2:08:50 PM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
WARNING: No rules found. Maybe you misspelled a rule name? (c:\x\x\x\x\.ruleset.xml)
```

```
Analyzing c:\x\x\x\x\WEB-INF\src\Portail\GestionnaireFavoris.java
stderr:juin 09, 2023 2:10:40 PM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
SEVERE: Cannot load ruleset c:\x\x\x\x\.ruleset.xml: Unable to find referenced rule NonSerializableClass; perhaps the rule name is misspelled?

stderr:juin 09, 2023 2:10:40 PM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
WARNING: No rules found. Maybe you misspelled a rule name? (c:\x\x\x\x\.ruleset.xml)
```

**Comment by cracrayol** [comment]
Got no error on my side.

Have you set the path to your custom ruleset in the plugin configuration ?
"javaPMD.rulesets": [
    "/home/cracrayol/dev/vscode-java-pmd/rulesets_test/ruleset.xml"
]

**Comment by Tenebrosful** [comment]
Yeah i correctly load my rule set `"javaPMD.rulesets": [".ruleset.xml"],` (unless i wouldn't get the error when i un-comment the rules)

Yeha i'm in `v0.7.0-rc`. 
![image](https://github.com/cracrayol/vscode-java-pmd/assets/48710891/9e56807c-d8e8-430d-a34c-7f7b213b4117)

**Comment by Tenebrosful** [comment]
This rules asides, looks like `v0.7.0-rc` throw this error

```
stderr:SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation

stderr:SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

3 issue(s) found
```

And false-report `UncessaryImport`, i checked in `v0.6.3` and it doesn't happen (here the 3 import of JUnit used in the file)

**Comment by Tenebrosful** [comment]
(Take opportunity to link this to global 7.0 update post) https://github.com/pmd/pmd/issues/3898
