### ISSUE TITLE
Not available on vscode extension marketplace?

### ISSUE THREAD

**Issue by adamDilger** [cracrayol/vscode-java-pmd#3]
Has this extension been removed from the marketplace? I'm not able to find it via searching. 

It can still be installed via the `vsix` file in the meantime, I just thought I'd follow up on whether this is a known issue or not. 

Thanks!

**Comment by cracrayol** [comment]
I don't know why but the extension has been unpublished and locked without any information from MS.

I'll to add it again but not sure if will works if I keep the same extension ID.

**Comment by c0va23** [comment]
is there any news?

**Comment by jestrella04** [comment]
I see other extensions were removed due to a 'copyright infringement' claim from Oracle because the name of the extension starts with the word Java. Likely also the case for this extension.

**Comment by c-simpson** [comment]
There seem to be a lot of extensions that start with, or include 'Java' in the name:
https://marketplace.visualstudio.com/search?term=java&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by cracrayol** [comment]
I've resend an email to vsmarketplace@microsoft.com. Hope this time will get a answer.
If no response, I'll have to change the extension's name in order to publish it again.

**Comment by cracrayol** [comment]
Ok, i've got the answer. It seems that some previous mails from MS was put into spam and never see that I was asked to modify the name of the extension : "Recently, we received an infringement complaint from Java Software | Oracle asking that your extension not use their copyrighted Coffee Cup with Steam Logo or include the word “Java” at the beginning of your extension’s display name."

I'll change the name and try to resend the extension to the marketplace.

**Comment by cracrayol** [comment]
Extension available on VS Marketplace : https://marketplace.visualstudio.com/items?itemName=cracrayol.pmd-java

Please remove any previous versions before installing this one.
